# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2014
  project: iw Immo (Deutsch)
  version: 0.0
  release: 0.0.1
  latex_documents:
  - - Index
    - iw_immo.tex
    - iw Immo
    - Immowelt AG
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
